# suppress inspection "UnusedProperty" for whole file
displayName=Simplifying Mixology
author=Thource
support=https://github.com/Thource/simplifying-mixology
description=Provides various QoL features to make Mastering Mixology better.
tags=mastering mixology,qol
plugins=dev.thource.runelite.simplifyingmixology.SimplifyingMixologyPlugin
build=standard
